import { chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";

export interface WorkspaceConfig {
  tenantId: string;
  whatsapp: {
    appSecret: string;
    accessToken: string;
    phoneNumberId: string;
    businessAccountId: string;
    verifyToken: string;
    apiVersion: string;
  };
  llm: {
    provider: "anthropic";
    apiKey: string;
    model: string;
  };
  server: {
    host: string;
    port: number;
    publicUrl?: string;
  };
}

export function defaultWorkspaceDir(): string {
  return process.env.CRAB_WORKSPACE_DIR
    ? process.env.CRAB_WORKSPACE_DIR.replace(/^~/, homedir())
    : join(homedir(), ".crab", "workspace");
}

export function configPath(workspaceDir = defaultWorkspaceDir()): string {
  return join(workspaceDir, "config.json");
}

export async function readConfig(workspaceDir = defaultWorkspaceDir()): Promise<WorkspaceConfig | undefined> {
  try {
    const raw = await readFile(configPath(workspaceDir), "utf8");
    return JSON.parse(raw) as WorkspaceConfig;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw err;
  }
}

export async function writeConfig(cfg: WorkspaceConfig, workspaceDir = defaultWorkspaceDir()): Promise<string> {
  await mkdir(workspaceDir, { recursive: true });
  const path = configPath(workspaceDir);
  await writeFile(path, JSON.stringify(cfg, null, 2), { mode: 0o600 });
  await chmod(path, 0o600);
  return path;
}

/** Render an .env file from a workspace config so docker-compose / hosts pick it up. */
export function renderEnvFile(cfg: WorkspaceConfig): string {
  return [
    `# Generated by 'crab onboard'. Edit with care.`,
    `CRAB_HOST=${cfg.server.host}`,
    `CRAB_PORT=${cfg.server.port}`,
    cfg.server.publicUrl ? `CRAB_PUBLIC_URL=${cfg.server.publicUrl}` : `# CRAB_PUBLIC_URL=`,
    ``,
    `WHATSAPP_APP_SECRET=${cfg.whatsapp.appSecret}`,
    `WHATSAPP_ACCESS_TOKEN=${cfg.whatsapp.accessToken}`,
    `WHATSAPP_PHONE_NUMBER_ID=${cfg.whatsapp.phoneNumberId}`,
    `WHATSAPP_BUSINESS_ACCOUNT_ID=${cfg.whatsapp.businessAccountId}`,
    `WHATSAPP_VERIFY_TOKEN=${cfg.whatsapp.verifyToken}`,
    `WHATSAPP_API_VERSION=${cfg.whatsapp.apiVersion}`,
    ``,
    `ANTHROPIC_API_KEY=${cfg.llm.apiKey}`,
    `CRAB_LLM_PROVIDER=${cfg.llm.provider}`,
    `CRAB_LLM_MODEL=${cfg.llm.model}`,
    ``,
  ].join("\n");
}
